# Generated by Django 6.0.4 on 2026-08-09 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_name', models.CharField(blank=True, help_text='若替代動作不在動作字典中，直接填名稱', max_length=100, verbose_name='替代動作名稱')),
                ('contraindicated_body_parts', models.JSONField(default=list, help_text='例：["HAMSTRING", "LOW_BACK"]', verbose_name='禁忌部位')),
                ('max_pain_level', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='可執行的最高疼痛值')),
                ('rationale', models.TextField(blank=True, verbose_name='原因')),
                ('original_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='training.exercise', verbose_name='原動作')),
                ('substitute_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutes_for', to='training.exercise', verbose_name='替代動作')),
            ],
            options={
                'verbose_name': '替代動作',
                'verbose_name_plural': '替代動作',
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('body_part', models.CharField(choices=[('HAMSTRING', '膕繩肌'), ('QUAD', '股四頭肌'), ('CALF', '小腿'), ('ACHILLES', '阿基里斯腱'), ('PLANTAR', '足底'), ('KNEE', '膝關節'), ('ANKLE', '踝關節'), ('HIP', '髖關節'), ('GROIN', '鼠蹊'), ('LOW_BACK', '下背'), ('SHOULDER', '肩部'), ('SHIN', '脛骨'), ('FOOT', '足部')], max_length=20, verbose_name='部位')),
                ('side', models.CharField(choices=[('LEFT', '左'), ('RIGHT', '右'), ('BILATERAL', '雙側'), ('NA', '不適用')], default='NA', max_length=10, verbose_name='側別')),
                ('injury_type', models.CharField(choices=[('STRAIN', '肌肉拉傷'), ('SPRAIN', '韌帶扭傷'), ('TENDINOPATHY', '肌腱病變/肌腱炎'), ('PERIOSTITIS', '骨膜炎'), ('STRESS_FRACTURE', '應力性骨折'), ('CONTUSION', '挫傷'), ('OVERUSE', '過度使用'), ('OTHER', '其他')], max_length=20, verbose_name='類型')),
                ('mechanism', models.TextField(blank=True, help_text='例：加速期第 3 步、落地瞬間、過度使用', verbose_name='受傷機制')),
                ('onset_date', models.DateField(verbose_name='受傷日期')),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='1: <7天 2: 7-28天 3: >28天 4: 賽季報銷', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='嚴重度 (1-4)')),
                ('status', models.CharField(choices=[('ACUTE', '急性期'), ('REHAB', '復健中'), ('RETURN_TO_RUN', '回歸跑動'), ('RESOLVED', '已康復')], default='ACUTE', max_length=15, verbose_name='狀態')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='預計回歸日期')),
                ('diagnosis', models.TextField(blank=True, verbose_name='診斷')),
                ('practitioner', models.CharField(blank=True, max_length=80, verbose_name='醫療人員')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '傷患',
                'verbose_name_plural': '傷患',
                'ordering': ['-onset_date'],
            },
        ),
        migrations.CreateModel(
            name='PainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('pain_at_rest', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='靜態疼痛 (0-10)')),
                ('pain_during_activity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='活動時疼痛 (0-10)')),
                ('swelling', models.BooleanField(default=False, verbose_name='腫脹')),
                ('rom_limited', models.BooleanField(default=False, verbose_name='活動度受限')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_logs', to='injury.injury')),
            ],
            options={
                'verbose_name': '疼痛日誌',
                'verbose_name_plural': '疼痛日誌',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RehabProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('phase', models.CharField(choices=[('PROTECTION', '保護期'), ('LOADING', '負荷期'), ('STRENGTH', '力量期'), ('RTP', '回歸運動期')], max_length=15, verbose_name='復健階段')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('progression_criteria', models.TextField(blank=True, verbose_name='進階條件')),
                ('is_current', models.BooleanField(default=True, verbose_name='目前階段')),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='injury.injury')),
            ],
            options={
                'verbose_name': '復健方案',
                'verbose_name_plural': '復健方案',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RehabExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='動作名稱')),
                ('sets', models.PositiveSmallIntegerField(default=3, verbose_name='組數')),
                ('reps', models.CharField(default='10', max_length=40, verbose_name='次數/時間')),
                ('frequency_per_week', models.PositiveSmallIntegerField(default=5, verbose_name='每週頻率')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='備註')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='injury.rehabprotocol')),
            ],
            options={
                'verbose_name': '復健動作',
                'verbose_name_plural': '復健動作',
            },
        ),
        migrations.AddIndex(
            model_name='injury',
            index=models.Index(fields=['athlete', 'status'], name='injury_inju_athlete_3b0bd3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='painlog',
            unique_together={('injury', 'date')},
        ),
    ]
