# Generated by Django 6.0.4 on 2026-08-30 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='next_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次覆診 / 檢視'),
        ),
        migrations.AddField(
            model_name='injury',
            name='treatment_direction',
            field=models.TextField(blank=True, help_text='這個傷要往哪個方向處理：目標、主要手段、下一步條件', verbose_name='治療方向'),
        ),
        migrations.AddField(
            model_name='injury',
            name='treatment_status',
            field=models.CharField(choices=[('ASSESS', '評估診斷'), ('RELIEVE', '消炎止痛'), ('RESTORE', '恢復功能'), ('RECONDITION', '重建體能')], default='ASSESS', max_length=15, verbose_name='治療進度'),
        ),
        migrations.CreateModel(
            name='TreatmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='治療日期')),
                ('treatment_type', models.CharField(choices=[('DOCTOR', '醫生診症'), ('IMAGING', '影像檢查'), ('PHYSIO', '物理治療'), ('MANUAL', '手法治療 / 推拿'), ('ACUPUNCTURE', '針灸 / 針刺'), ('ICE', '冰敷 / 冷療'), ('HEAT', '熱敷'), ('STRETCH', '伸展 / 筋膜放鬆'), ('STRENGTH', '復健強化訓練'), ('TAPING', '貼紮 / 護具'), ('MEDICATION', '藥物'), ('SURGERY', '手術'), ('REST', '完全休息'), ('OTHER', '其他')], max_length=15, verbose_name='治療手段')),
                ('provider', models.CharField(blank=True, help_text='例：陳physio、XX 骨科', max_length=100, verbose_name='治療者 / 機構')),
                ('content', models.TextField(blank=True, help_text='做了什麼、劑量或時間', verbose_name='處理內容')),
                ('effect', models.PositiveSmallIntegerField(choices=[(1, '明顯改善'), (2, '略有改善'), (3, '無變化'), (4, '變差')], default=3, verbose_name='成效')),
                ('pain_after', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='治療後疼痛 (0-10)')),
                ('next_step', models.CharField(blank=True, max_length=200, verbose_name='下一步')),
                ('cost_hkd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='費用 (HKD)')),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='injury.injury')),
            ],
            options={
                'verbose_name': '治療紀錄',
                'verbose_name_plural': '治療紀錄',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['injury', 'date'], name='injury_trea_injury__624842_idx')],
            },
        ),
    ]
