# Generated by Django 6.0.4 on 2026-09-05 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0002_injury_next_review_date_injury_treatment_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='rtp_progress',
            field=models.JSONField(blank=True, default=list, help_text='已勾選的 Return-to-Play 條件索引', verbose_name='RTP 已達成條件'),
        ),
        migrations.AddField(
            model_name='injury',
            name='training_mode',
            field=models.CharField(choices=[('FULL_REST', '完全休養'), ('REHAB_ONLY', '只做康復'), ('MODIFIED', '調整訓練'), ('GRADUAL', '漸進回歸'), ('FULL', '完全訓練')], default='MODIFIED', help_text='今天這個人怎麼練：完全休養 / 只做康復 / 調整訓練 / 漸進回歸 / 完全訓練', max_length=15, verbose_name='訓練處理方式'),
        ),
        migrations.AddField(
            model_name='injury',
            name='training_note',
            field=models.CharField(blank=True, help_text='給教練看的一句話，例：只做上肢與核心，禁跑跳', max_length=200, verbose_name='訓練備註'),
        ),
        migrations.AddField(
            model_name='painlog',
            name='load_intensity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='用幾分力做：投球力度、跑速、重量。10 = 全力', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='今日強度（幾分力 0-10）'),
        ),
        migrations.AddField(
            model_name='painlog',
            name='load_volume',
            field=models.CharField(blank=True, help_text='做了多少：例 投 30 球 / 慢跑 3km / 深蹲 60kg×3×8', max_length=120, verbose_name='今日總量'),
        ),
        migrations.AddField(
            model_name='painlog',
            name='pain_after_session',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='運動結束後疼痛 (0-10)'),
        ),
        migrations.AddField(
            model_name='painlog',
            name='pain_before',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='今早／運動前疼痛 (0-10)'),
        ),
    ]
