# Generated by Django 6.0.4 on 2026-09-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury', '0003_injury_rtp_progress_injury_training_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painlog',
            name='day_action',
            field=models.CharField(blank=True, choices=[('AS_USUAL', '可照常訓練'), ('REDUCE', '減低訓練量'), ('CHANGE', '改變訓練方向'), ('REST', '完全休息')], help_text='照常訓練 / 減低訓練量 / 改變訓練方向 / 完全休息', max_length=10, verbose_name='今日決定'),
        ),
    ]
