# Generated by Django 6.0.4 on 2026-08-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_load_au', models.PositiveIntegerField(default=0, verbose_name='總負荷 (AU)')),
                ('track_volume_m', models.PositiveIntegerField(default=0, verbose_name='專項總量 (m)')),
                ('strength_tonnage_kg', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='力量總噸位 (kg)')),
                ('session_count', models.PositiveSmallIntegerField(default=0, verbose_name='課次')),
                ('avg_rpe', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='平均 RPE')),
                ('duration_min', models.PositiveIntegerField(default=0, verbose_name='總時長 (分)')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_loads', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '每日負荷',
                'verbose_name_plural': '每日負荷',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['athlete', 'date'], name='analytics_d_athlete_165a99_idx')],
                'unique_together': {('athlete', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('week_start', models.DateField(verbose_name='週一日期')),
                ('total_load', models.PositiveIntegerField(default=0, verbose_name='週總負荷 (AU)')),
                ('monotony', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='單調度')),
                ('strain', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='訓練張力')),
                ('acwr', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ACWR')),
                ('acute_load', models.PositiveIntegerField(default=0, verbose_name='急性負荷 (7d)')),
                ('chronic_load', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='慢性負荷 (28d/4)')),
                ('week_over_week_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='週增幅 (%)')),
                ('risk_flag', models.CharField(choices=[('UNDER', '訓練不足'), ('OPTIMAL', '甜蜜點'), ('ELEVATED', '負荷偏高'), ('HIGH', '高受傷風險'), ('INSUFFICIENT', '資料累積中')], default='INSUFFICIENT', max_length=15, verbose_name='風險判定')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '週彙總',
                'verbose_name_plural': '週彙總',
                'ordering': ['-week_start'],
                'unique_together': {('athlete', 'week_start')},
            },
        ),
    ]
