# Generated by Django 6.0.4 on 2026-08-30 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('analytics', '0001_initial'),
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('COMPETITION', '比賽數據'), ('TRACK', '田徑練習訓練紀錄'), ('STRENGTH', '重量訓練紀錄')], max_length=15, verbose_name='範疇')),
                ('name', models.CharField(max_length=60, verbose_name='項目名稱')),
                ('unit', models.CharField(blank=True, help_text='例：秒、m、kg、cm', max_length=15, verbose_name='單位')),
                ('higher_is_better', models.BooleanField(default=True, help_text='計時類項目請取消勾選（越小越好）', verbose_name='數值越大越好')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='內建項目')),
                ('is_active', models.BooleanField(default=True, verbose_name='顯示中')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_items', to=settings.AUTH_USER_MODEL, verbose_name='新增者')),
            ],
            options={
                'verbose_name': '數據項目',
                'verbose_name_plural': '數據項目',
                'ordering': ['domain', '-is_builtin', 'name'],
                'unique_together': {('domain', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='數值')),
                ('context', models.CharField(blank=True, help_text='例：順風 1.2、賽前熱身、第 3 組', max_length=120, verbose_name='情境')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_records', to='accounts.athleteprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analytics.metricitem')),
                ('session', models.ForeignKey(blank=True, help_text='留空表示不是從日曆的課表產生（例如比賽）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_records', to='planning.trainingsession', verbose_name='對應 program')),
            ],
            options={
                'verbose_name': '數據紀錄',
                'verbose_name_plural': '數據紀錄',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['athlete', 'item', 'date'], name='analytics_m_athlete_1d542a_idx')],
            },
        ),
    ]
