# Generated by Django 6.0.4 on 2026-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_metricitem_metricrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricrecord',
            name='completed',
            field=models.BooleanField(default=True, help_text='這一組有沒有照課表完成（沒完成請取消勾選）', verbose_name='成功完成'),
        ),
        migrations.AddField(
            model_name='metricrecord',
            name='reps',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='次數'),
        ),
        migrations.AddField(
            model_name='metricrecord',
            name='rest_sec',
            field=models.PositiveIntegerField(blank=True, help_text='這一組做完之後休息幾秒', null=True, verbose_name='休息時間 (秒)'),
        ),
        migrations.AddField(
            model_name='metricrecord',
            name='set_no',
            field=models.PositiveSmallIntegerField(blank=True, help_text='第幾組；單筆成績（例如比賽）可留空', null=True, verbose_name='組別'),
        ),
        migrations.AddField(
            model_name='metricrecord',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='重量 (kg)'),
        ),
    ]
