# Generated by Django 6.0.4 on 2026-09-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_metricrecord_completed_metricrecord_reps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricitem',
            options={'ordering': ['domain', 'category', '-is_builtin', 'name'], 'verbose_name': '數據項目', 'verbose_name_plural': '數據項目'},
        ),
        migrations.AddField(
            model_name='metricitem',
            name='category',
            field=models.CharField(choices=[('WARMUP', '熱身動作（Warm-up Activities）'), ('UPPER', '上身動作（Upper Body Movement）'), ('LOWER', '下身動作（Lower Body Movement）'), ('CORE', '核心肌群（Core Strength）'), ('FULL', '全身力量（Full-Body Workout）'), ('PLYO', '增強式訓練（Plyometric Training）'), ('OTHER', '其他')], default='OTHER', help_text='重量訓練紀錄的項目清單依這個分組顯示', max_length=10, verbose_name='動作分類'),
        ),
    ]
