# Generated by Django 6.0.4 on 2026-09-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_metricitem_options_metricitem_category'),
        ('planning', '0004_alter_phase_phase_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricitem',
            name='name_en',
            field=models.CharField(blank=True, help_text='清單與紀錄都以「中文（English）」顯示，兩個名字都找得到', max_length=80, verbose_name='英文名稱'),
        ),
        migrations.AddField(
            model_name='metricrecord',
            name='competition',
            field=models.ForeignKey(blank=True, help_text='比賽數據登在哪一場比賽底下；練習紀錄留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_records', to='planning.competition', verbose_name='賽事'),
        ),
    ]
