# Generated by Django 6.0.4 on 2026-09-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_metricitem_name_en_metricrecord_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricrecord',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='課表上要求的目標，沒有就留空', max_digits=10, null=True, verbose_name='目標數值 (秒)'),
        ),
        migrations.AlterField(
            model_name='metricrecord',
            name='rest_sec',
            field=models.PositiveIntegerField(blank=True, help_text='這一組做完之後休息多久；表單可以用秒或分鐘填，一律換算成秒存起來', null=True, verbose_name='休息時間 (秒)'),
        ),
        migrations.AlterField(
            model_name='metricrecord',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='實際完成的數值，還沒量到可以留空，之後在數據分析補', max_digits=10, null=True, verbose_name='完成數值 (秒)'),
        ),
    ]
