# Generated by Django 6.0.4 on 2026-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_metricrecord_target_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricrecord',
            name='intensity',
            field=models.CharField(blank=True, help_text='田徑練習這一組要求的強度，例：90%、95%、全力', max_length=20, verbose_name='強度要求'),
        ),
    ]
