# Generated by Django 6.0.4 on 2026-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_metricrecord_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricitem',
            name='track_distance_m',
            field=models.PositiveIntegerField(blank=True, help_text='田徑練習專用：這個項目跑幾米', null=True, verbose_name='距離 (m)'),
        ),
        migrations.AddField(
            model_name='metricitem',
            name='track_method',
            field=models.CharField(blank=True, choices=[('TEMPO', '節奏跑'), ('REPEAT', '反覆跑'), ('INTERVAL', '間歇跑'), ('START', '起跑'), ('ACCEL', '加速跑'), ('BUILDUP', '漸速跑'), ('FLYING', '飛行跑'), ('MAXSPEED', '全速計時'), ('SPLIT', '分段跑'), ('HILL', '上坡跑'), ('RESIST', '阻力跑'), ('HURDLE', '跨欄節奏'), ('RELAY', '接力交棒'), ('TECH', '技術跑'), ('ENDURANCE', '專項耐力跑')], help_text='田徑練習專用：節奏跑／反覆跑／起跑／加速跑…', max_length=12, verbose_name='練習方式'),
        ),
        migrations.AddField(
            model_name='metricrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('OFFSEASON', '季後休息期'), ('PREP', '訓練準備期'), ('TAPER', '比賽調整期'), ('INJURY', '傷害治療期'), ('RETURN', '恢復回歸期')], help_text='這天的練習在什麼狀態下進行（季後休息／訓練準備／比賽調整／傷害治療／恢復回歸）', max_length=12, verbose_name='狀態'),
        ),
    ]
