# Generated by Django 6.0.4 on 2026-09-04 15:42

import analytics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_metricitem_track_distance_m_metricitem_track_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricrecord',
            name='block',
            field=models.CharField(blank=True, choices=analytics.models.block_choices, help_text='這一組屬於課表的哪一段：熱身／正課／補充練習／恢復練習', max_length=12, verbose_name='課表區塊'),
        ),
    ]
