# Generated by Django 6.0.4 on 2026-09-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bodymetriclog_body_fat_mass_kg_bodymetriclog_brand_and_more'),
        ('analytics', '0009_metricrecord_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedMetricItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_items', to='accounts.athleteprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='analytics.metricitem', verbose_name='項目')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_pins', to=settings.AUTH_USER_MODEL, verbose_name='釘選者')),
            ],
            options={
                'verbose_name': '必看項目',
                'verbose_name_plural': '必看項目',
                'ordering': ['item__domain', 'id'],
                'unique_together': {('athlete', 'item')},
            },
        ),
    ]
