# Generated by Django 6.0.4 on 2026-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_pinnedmetricitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricrecord',
            name='distance_m',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='這一組跑／做的距離（米），沒有距離的動作留空', max_digits=8, null=True, verbose_name='距離 (m)'),
        ),
    ]
