# Generated by Django 6.0.4 on 2026-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_metricrecord_distance_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricitem',
            name='domain',
            field=models.CharField(choices=[('TRACK', '田徑練習訓練紀錄'), ('STRENGTH', '重量訓練紀錄'), ('COMPETITION', '比賽數據')], max_length=15, verbose_name='範疇'),
        ),
    ]
