# Generated by Django 6.0.4 on 2026-08-09 10:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='代碼')),
                ('name_zh', models.CharField(max_length=50, verbose_name='中文名稱')),
                ('name_en', models.CharField(max_length=50, verbose_name='英文名稱')),
                ('category', models.CharField(choices=[('SPRINT', '短跑'), ('HURDLES', '跨欄'), ('MIDDLE', '中距離'), ('DISTANCE', '長距離'), ('JUMP', '跳部'), ('THROW', '投擲'), ('COMBINED', '全能'), ('RELAY', '接力')], max_length=15, verbose_name='類別')),
                ('unit', models.CharField(choices=[('TIME', '時間 (秒)'), ('DISTANCE', '距離 (公尺)'), ('POINTS', '分數')], max_length=10, verbose_name='計量單位')),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='距離 (m)')),
            ],
            options={
                'verbose_name': '田徑項目',
                'verbose_name_plural': '田徑項目',
                'ordering': ['category', 'distance_m', 'code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('COACH', '教練'), ('ATHLETE', '運動員'), ('ADMIN', '管理員')], default='ATHLETE', max_length=10, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='頭像')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('squad_name', models.CharField(blank=True, max_length=80, verbose_name='組別名稱')),
                ('specialties', models.CharField(blank=True, max_length=120, verbose_name='專長')),
                ('certification', models.CharField(blank=True, max_length=120, verbose_name='執照')),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0, verbose_name='執教年資')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教練檔案',
                'verbose_name_plural': '教練檔案',
            },
        ),
        migrations.CreateModel(
            name='AthleteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別')),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='身高 (cm)')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='體重 (kg)')),
                ('training_days_per_week', models.PositiveSmallIntegerField(default=5, verbose_name='每週訓練日數')),
                ('strength_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='力量訓練年資')),
                ('status', models.CharField(choices=[('HEALTHY', '健康'), ('NIGGLE', '輕微不適'), ('INJURED', '傷患中')], default='HEALTHY', max_length=10, verbose_name='目前狀態')),
                ('school_or_club', models.CharField(blank=True, max_length=100, verbose_name='學校/會所')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_profile', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='accounts.coachprofile', verbose_name='所屬教練')),
                ('primary_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_athletes', to='accounts.event', verbose_name='主項')),
                ('secondary_events', models.ManyToManyField(blank=True, related_name='secondary_athletes', to='accounts.event', verbose_name='副項')),
            ],
            options={
                'verbose_name': '運動員檔案',
                'verbose_name_plural': '運動員檔案',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='BodyMetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='體重 (kg)')),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='體脂率 (%)')),
                ('resting_hr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='靜息心率')),
                ('hrv', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HRV (ms)')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '體測紀錄',
                'verbose_name_plural': '體測紀錄',
                'ordering': ['-date'],
                'unique_together': {('athlete', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PersonalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('mark', models.DecimalField(decimal_places=2, help_text='時間存秒，距離存公尺', max_digits=8, verbose_name='成績')),
                ('wind', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='風速 (m/s)')),
                ('date', models.DateField(verbose_name='創造日期')),
                ('competition_name', models.CharField(blank=True, max_length=120, verbose_name='賽事名稱')),
                ('is_current', models.BooleanField(default=True, verbose_name='目前最佳')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to='accounts.athleteprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_bests', to='accounts.event')),
            ],
            options={
                'verbose_name': '個人最佳',
                'verbose_name_plural': '個人最佳',
                'ordering': ['-date'],
                'unique_together': {('athlete', 'event', 'date')},
            },
        ),
    ]
