# Generated by Django 6.0.4 on 2026-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '管理員', 'verbose_name_plural': '管理員'},
        ),
    ]
