# Generated by Django 6.0.4 on 2026-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodymetriclog',
            options={'ordering': ['-date'], 'verbose_name': '體組成紀錄', 'verbose_name_plural': '體組成紀錄'},
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='bmr_kcal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='基礎代謝量 (kcal)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='body_water_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='體水分率 (%)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='bone_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='推定骨量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='device',
            field=models.CharField(blank=True, help_text='例：RD-545AS', max_length=40, verbose_name='量測機型'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='fat_arm_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='左上肢脂肪率 (%)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='fat_arm_r',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='右上肢脂肪率 (%)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='fat_leg_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='左腳脂肪率 (%)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='fat_leg_r',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='右腳脂肪率 (%)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='fat_trunk',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='軀幹部位脂肪率 (%)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='mba_rating',
            field=models.CharField(blank=True, max_length=20, verbose_name='MBA 判定'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='measured_at',
            field=models.TimeField(blank=True, null=True, verbose_name='量測時間'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='metabolic_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='體內年齡 (歲)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='mq_arm_l',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='左上肢肌肉品質點數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='mq_arm_r',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='右上肢肌肉品質點數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='mq_leg_l',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='左腳肌肉品質點數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='mq_leg_r',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='右腳肌肉品質點數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_arm_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='左上肢肌肉量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_arm_r',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='右上肢肌肉量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_leg_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='左腳肌肉量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_leg_r',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='右腳肌肉量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_mass_index',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='肌肉量判定指數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='肌肉量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_quality_score',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='肌肉質量指數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='muscle_trunk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='軀幹部位肌肉量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='note',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='source',
            field=models.CharField(choices=[('MANUAL', '手動輸入'), ('IMPORT', '檔案匯入')], default='MANUAL', max_length=10, verbose_name='來源'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='source_file',
            field=models.CharField(blank=True, max_length=120, verbose_name='匯入檔名'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='visceral_fat_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='內臟脂肪等級'),
        ),
        migrations.AlterField(
            model_name='bodymetriclog',
            name='body_fat_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='體脂肪率 (%)'),
        ),
    ]
