# Generated by Django 6.0.4 on 2026-09-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bodymetriclog_options_bodymetriclog_bmi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('zh-hant', '繁體中文'), ('en', 'English')], default='zh-hant', max_length=10, verbose_name='介面語言'),
        ),
    ]
