# Generated by Django 6.0.4 on 2026-09-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodymetriclog',
            name='body_fat_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='體脂肪量 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='brand',
            field=models.CharField(choices=[('GENERIC', '通用（Tanita 等）'), ('INBODY', 'InBody'), ('HOWBODY', 'HOWBODY')], default='GENERIC', help_text='報告紙上的項目名依品牌而異（InBody／HOWBODY／通用）。', max_length=10, verbose_name='量測品牌'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='ecw_tbw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='細胞外水分比 ECW/TBW'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='fat_free_mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='去脂體重 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='mineral_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='無機鹽／礦物質 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='protein_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='蛋白質 (kg)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='體組成分數'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='tbw_liters',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='身體總水分 (L)'),
        ),
        migrations.AddField(
            model_name='bodymetriclog',
            name='whr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='腰臀圍比 WHR'),
        ),
    ]
