# Generated by Django 6.0.4 on 2026-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bodymetriclog_body_fat_mass_kg_bodymetriclog_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteprofile',
            name='video_max_mb',
            field=models.PositiveIntegerField(blank=True, help_text='留空＝跟方案的預設值；0 ＝ 不限', null=True, verbose_name='影片容量上限 (MB)'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='video_max_videos',
            field=models.PositiveSmallIntegerField(blank=True, help_text='留空＝跟方案的預設值；0 ＝ 不限', null=True, verbose_name='影片條數上限'),
        ),
        migrations.AddField(
            model_name='athleteprofile',
            name='video_plan',
            field=models.CharField(choices=[('FREE', '免費'), ('PRO', '進階會員')], default='FREE', max_length=6, verbose_name='影片方案'),
        ),
    ]
