# Generated by Django 6.0.4 on 2026-08-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=150, verbose_name='賽事名稱')),
                ('date', models.DateField(verbose_name='比賽日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('venue', models.CharField(blank=True, max_length=150, verbose_name='場地')),
                ('level', models.CharField(choices=[('SCHOOL', '校際'), ('REGIONAL', '地區/公開賽'), ('NATIONAL', '全國錦標賽'), ('INTL', '國際賽')], default='REGIONAL', max_length=10, verbose_name='層級')),
                ('is_target', models.BooleanField(default=False, verbose_name='主目標賽事')),
            ],
            options={
                'verbose_name': '賽事',
                'verbose_name_plural': '賽事',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Macrocycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('total_weeks', models.PositiveSmallIntegerField(default=16, verbose_name='總週數')),
                ('baseline_weekly_load', models.PositiveIntegerField(default=1800, help_text='準備期的目標週負荷，其餘期別按係數換算', verbose_name='基準週負荷 (AU)')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macrocycles', to='accounts.athleteprofile')),
                ('target_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='macrocycles', to='planning.competition')),
            ],
            options={
                'verbose_name': '備戰大週期',
                'verbose_name_plural': '備戰大週期',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('GENERAL_PREP', '準備期'), ('SPECIFIC_PREP', '專項期'), ('PRE_COMP', '賽前期'), ('TAPER_COMP', '比賽期'), ('TRANSITION', '恢復期')], max_length=20, verbose_name='期別')),
                ('week_start', models.PositiveSmallIntegerField(verbose_name='起始週')),
                ('week_end', models.PositiveSmallIntegerField(verbose_name='結束週')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('focus', models.TextField(blank=True, verbose_name='訓練重心')),
                ('target_weekly_load', models.PositiveIntegerField(default=0, verbose_name='目標週負荷 (AU)')),
                ('macrocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='planning.macrocycle')),
            ],
            options={
                'verbose_name': '分期',
                'verbose_name_plural': '分期',
                'ordering': ['week_start'],
            },
        ),
        migrations.CreateModel(
            name='Microcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='週次')),
                ('start_date', models.DateField(verbose_name='週一日期')),
                ('planned_load', models.PositiveIntegerField(default=0, verbose_name='計劃負荷 (AU)')),
                ('actual_load', models.PositiveIntegerField(default=0, verbose_name='實際負荷 (AU)')),
                ('notes', models.TextField(blank=True, verbose_name='週計劃備註')),
                ('macrocycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microcycles', to='planning.macrocycle')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='microcycles', to='planning.phase')),
            ],
            options={
                'verbose_name': '週計劃',
                'verbose_name_plural': '週計劃',
                'ordering': ['week_number'],
                'unique_together': {('macrocycle', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=150, verbose_name='模板名稱')),
                ('session_type', models.CharField(choices=[('TRACK', '田徑專項'), ('STRENGTH', '力量訓練'), ('TECHNIQUE', '技術訓練'), ('RECOVERY', '恢復訓練'), ('CROSS_TRAINING', '交叉訓練'), ('COMPETITION', '比賽'), ('REST', '休息')], max_length=20, verbose_name='課別')),
                ('planned_duration_min', models.PositiveSmallIntegerField(default=90, verbose_name='計劃時長 (分)')),
                ('description', models.TextField(blank=True, verbose_name='課表內容')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='結構化內容')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_templates', to='accounts.coachprofile')),
            ],
            options={
                'verbose_name': '課表模板',
                'verbose_name_plural': '課表模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('target_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='目標成績')),
                ('result_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='實際成績')),
                ('placing', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='名次')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_entries', to='accounts.athleteprofile')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='planning.competition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
            ],
            options={
                'verbose_name': '參賽項目',
                'verbose_name_plural': '參賽項目',
                'unique_together': {('competition', 'athlete', 'event')},
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('time_slot', models.CharField(choices=[('AM', '上午'), ('PM', '下午')], default='PM', max_length=2, verbose_name='時段')),
                ('session_type', models.CharField(choices=[('TRACK', '田徑專項'), ('STRENGTH', '力量訓練'), ('TECHNIQUE', '技術訓練'), ('RECOVERY', '恢復訓練'), ('CROSS_TRAINING', '交叉訓練'), ('COMPETITION', '比賽'), ('REST', '休息')], max_length=20, verbose_name='課別')),
                ('title', models.CharField(max_length=150, verbose_name='課表名稱')),
                ('description', models.TextField(blank=True, verbose_name='課表內容')),
                ('planned_duration_min', models.PositiveSmallIntegerField(default=90, verbose_name='計劃時長 (分)')),
                ('actual_duration_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='實際時長 (分)')),
                ('status', models.CharField(choices=[('PLANNED', '已排定'), ('COMPLETED', '已完成'), ('PARTIAL', '部分完成'), ('SKIPPED', '未執行')], default='PLANNED', max_length=10, verbose_name='狀態')),
                ('completion_pct', models.PositiveSmallIntegerField(default=0, verbose_name='完成度 (%)')),
                ('session_rpe', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='課後 RPE (1-10)')),
                ('is_modified', models.BooleanField(default=False, verbose_name='傷患調整後課表')),
                ('athlete_feedback', models.TextField(blank=True, verbose_name='運動員反饋')),
                ('coach_comment', models.TextField(blank=True, verbose_name='教練評語')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='留空表示運動員自訂', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sessions', to='accounts.coachprofile', verbose_name='派發教練')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.athleteprofile')),
                ('microcycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='planning.microcycle')),
            ],
            options={
                'verbose_name': '訓練課',
                'verbose_name_plural': '訓練課',
                'ordering': ['-date', 'time_slot'],
                'indexes': [models.Index(fields=['athlete', 'date'], name='planning_tr_athlete_e07a54_idx'), models.Index(fields=['athlete', 'status'], name='planning_tr_athlete_865a5d_idx')],
            },
        ),
    ]
