# Generated by Django 6.0.4 on 2026-08-30 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('planning', '0001_initial'),
        ('programs', '0002_remove_application_guardian_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontemplate',
            name='session_type',
            field=models.CharField(choices=[('TRACK', '田徑場訓練'), ('STRENGTH', '重量訓練'), ('RECOVERY', '恢復訓練'), ('REHAB', '治療康復'), ('OTHER', '其他'), ('TECHNIQUE', '技術訓練'), ('CROSS_TRAINING', '交叉訓練'), ('COMPETITION', '比賽'), ('REST', '休息')], max_length=20, verbose_name='課別'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(choices=[('TRACK', '田徑場訓練'), ('STRENGTH', '重量訓練'), ('RECOVERY', '恢復訓練'), ('REHAB', '治療康復'), ('OTHER', '其他'), ('TECHNIQUE', '技術訓練'), ('CROSS_TRAINING', '交叉訓練'), ('COMPETITION', '比賽'), ('REST', '休息')], max_length=20, verbose_name='課別'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='生效中')),
                ('note', models.TextField(blank=True, help_text='例：只負責短跑組、每週二四帶課', verbose_name='分配備註')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='分配者')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='accounts.coachprofile', verbose_name='負責教練')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='programs.project', verbose_name='報名項目')),
            ],
            options={
                'verbose_name': '項目分配',
                'verbose_name_plural': '項目分配',
                'ordering': ['project__display_order', 'coach__user__username'],
                'unique_together': {('project', 'coach')},
            },
        ),
    ]
