# Generated by Django 6.0.4 on 2026-08-31 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_sessiontemplate_session_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='誰把這堂課寫進日曆的；只有他自己（和管理員）能改課表本身', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='satisfaction',
            field=models.PositiveSmallIntegerField(blank=True, help_text='完成訓練後自評：這一課練得滿不滿意', null=True, verbose_name='訓練滿意度 (1-5)'),
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('kind', models.CharField(choices=[('POINT', '訓練要點'), ('NOTE', '當日備注'), ('FEEDBACK', '訓練反饋')], default='NOTE', max_length=10, verbose_name='類別')),
                ('body', models.TextField(verbose_name='內容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL, verbose_name='寫入者')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='planning.trainingsession')),
            ],
            options={
                'verbose_name': '課表記事',
                'verbose_name_plural': '課表記事',
                'ordering': ['created_at'],
            },
        ),
    ]
