# Generated by Django 6.0.4 on 2026-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_trainingsession_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='phase_type',
            field=models.CharField(choices=[('GENERAL_PREP', '一般準備期'), ('SPECIFIC_PREP', '專項準備期'), ('PRE_COMP', '賽前期'), ('TAPER_COMP', '比賽期'), ('TRANSITION', '過渡期')], max_length=20, verbose_name='期別'),
        ),
        migrations.AlterField(
            model_name='sessiontemplate',
            name='session_type',
            field=models.CharField(choices=[('TRACK', '田徑場訓練'), ('STRENGTH', '重量訓練'), ('RECOVERY', '恢復訓練'), ('REHAB', '治療康復'), ('COMPETITION', '比賽'), ('OTHER', '其他'), ('TECHNIQUE', '技術訓練'), ('CROSS_TRAINING', '交叉訓練'), ('REST', '休息')], max_length=20, verbose_name='課別'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_type',
            field=models.CharField(choices=[('TRACK', '田徑場訓練'), ('STRENGTH', '重量訓練'), ('RECOVERY', '恢復訓練'), ('REHAB', '治療康復'), ('COMPETITION', '比賽'), ('OTHER', '其他'), ('TECHNIQUE', '技術訓練'), ('CROSS_TRAINING', '交叉訓練'), ('REST', '休息')], max_length=20, verbose_name='課別'),
        ),
    ]
