# Generated by Django 6.0.4 on 2026-08-09 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='恢復手段')),
                ('category', models.CharField(blank=True, max_length=40, verbose_name='分類')),
                ('default_duration_min', models.PositiveSmallIntegerField(default=10, verbose_name='建議時長 (分)')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '恢復手段',
                'verbose_name_plural': '恢復手段',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('name', models.CharField(max_length=80, verbose_name='補充劑')),
                ('dose', models.CharField(max_length=50, verbose_name='劑量')),
                ('timing', models.CharField(blank=True, max_length=80, verbose_name='服用時機')),
                ('purpose', models.CharField(blank=True, max_length=120, verbose_name='目的')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '補充劑紀錄',
                'verbose_name_plural': '補充劑紀錄',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', '早餐'), ('LUNCH', '午餐'), ('DINNER', '晚餐'), ('PRE_TRAINING', '訓練前'), ('POST_TRAINING', '訓練後'), ('SNACK', '加餐')], max_length=15, verbose_name='餐次')),
                ('description', models.TextField(verbose_name='內容')),
                ('kcal', models.PositiveIntegerField(default=0, verbose_name='熱量 (kcal)')),
                ('carb_g', models.PositiveIntegerField(default=0, verbose_name='碳水 (g)')),
                ('protein_g', models.PositiveIntegerField(default=0, verbose_name='蛋白質 (g)')),
                ('fat_g', models.PositiveIntegerField(default=0, verbose_name='脂肪 (g)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meals/', verbose_name='餐點照片')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '飲食紀錄',
                'verbose_name_plural': '飲食紀錄',
                'ordering': ['-date', 'meal_type'],
                'indexes': [models.Index(fields=['athlete', 'date'], name='nutrition_m_athlete_559a17_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('day_type', models.CharField(choices=[('HARD', '高強度日'), ('MODERATE', '中強度日'), ('EASY', '輕度日'), ('REST', '休息日'), ('COMPETITION', '比賽日')], max_length=15, verbose_name='訓練日類型')),
                ('goal', models.CharField(choices=[('LOSE', '減脂'), ('MAINTAIN', '維持'), ('GAIN', '增重')], default='MAINTAIN', max_length=10, verbose_name='體重目標')),
                ('bmr_kcal', models.PositiveIntegerField(default=0, verbose_name='BMR (kcal)')),
                ('tdee_kcal', models.PositiveIntegerField(default=0, verbose_name='TDEE (kcal)')),
                ('target_kcal', models.PositiveIntegerField(default=0, verbose_name='目標熱量 (kcal)')),
                ('carb_g', models.PositiveIntegerField(default=0, verbose_name='碳水 (g)')),
                ('protein_g', models.PositiveIntegerField(default=0, verbose_name='蛋白質 (g)')),
                ('fat_g', models.PositiveIntegerField(default=0, verbose_name='脂肪 (g)')),
                ('water_ml', models.PositiveIntegerField(default=0, verbose_name='水份 (ml)')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '每日營養目標',
                'verbose_name_plural': '每日營養目標',
                'ordering': ['-date'],
                'unique_together': {('athlete', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='睡眠時長 (小時)')),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='睡眠質量 (1-5)')),
                ('bedtime', models.TimeField(blank=True, null=True, verbose_name='就寢時間')),
                ('wake_time', models.TimeField(blank=True, null=True, verbose_name='起床時間')),
                ('water_intake_ml', models.PositiveIntegerField(default=0, verbose_name='飲水量 (ml)')),
                ('soreness_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='肌肉痠痛 (1-10)')),
                ('stress_level', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='壓力 (1-5)')),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='心情 (1-5)')),
                ('resting_hr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='晨脈')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_logs', to='accounts.athleteprofile')),
                ('methods', models.ManyToManyField(blank=True, related_name='logs', to='nutrition.recoverymethod', verbose_name='使用的恢復手段')),
            ],
            options={
                'verbose_name': '恢復日誌',
                'verbose_name_plural': '恢復日誌',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['athlete', 'date'], name='nutrition_r_athlete_3ff510_idx')],
                'unique_together': {('athlete', 'date')},
            },
        ),
    ]
