# Generated by Django 6.0.4 on 2026-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_zh', models.CharField(max_length=60, unique=True, verbose_name='名稱')),
                ('aliases', models.CharField(blank=True, help_text='逗號分隔，例：雞胸,雞扒,chicken breast', max_length=200, verbose_name='別名')),
                ('category', models.CharField(blank=True, max_length=40, verbose_name='分類')),
                ('kcal_per_100g', models.PositiveIntegerField(default=0, verbose_name='熱量 (kcal/100g)')),
                ('carb_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='碳水 (g/100g)')),
                ('protein_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='蛋白質 (g/100g)')),
                ('fat_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='脂肪 (g/100g)')),
                ('fiber_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='膳食纖維 (g/100g)')),
                ('sodium_mg_per_100g', models.PositiveIntegerField(default=0, verbose_name='鈉 (mg/100g)')),
                ('typical_serving_g', models.PositiveIntegerField(default=100, verbose_name='常見一份 (g)')),
                ('serving_label', models.CharField(blank=True, help_text='例：一碗、一隻', max_length=40, verbose_name='一份的說法')),
            ],
            options={
                'verbose_name': '食物字典',
                'verbose_name_plural': '食物字典',
                'ordering': ['category', 'name_zh'],
            },
        ),
        migrations.AddField(
            model_name='meallog',
            name='analysis_note',
            field=models.TextField(blank=True, verbose_name='辨識說明 / 評估'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='analysis_source',
            field=models.CharField(choices=[('MANUAL', '手動輸入'), ('PHOTO_AI', '相片辨識（AI）'), ('DICTIONARY', '文字比對食物字典')], default='MANUAL', max_length=15, verbose_name='營養來源'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fiber_g',
            field=models.PositiveIntegerField(default=0, verbose_name='膳食纖維 (g)'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "白飯", "grams": 200, "kcal": 260, ...}]', verbose_name='辨識出的品項'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='sodium_mg',
            field=models.PositiveIntegerField(default=0, verbose_name='鈉 (mg)'),
        ),
    ]
