"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# ---------------------------------------------------------------- 環境設定
# 本機開發用預設值；正式環境一律用環境變數覆蓋（Render → Environment）。

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-i790o7p$k$@fi=(k$(0y_&zcoz%6ngr@q6jby=-buk!(vp_7vo",
)

# DJANGO_DEBUG=0 關閉（Render 上務必設為 0）
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]", "testserver"]

# 自訂網域，用逗號分隔：DJANGO_ALLOWED_HOSTS=www.hohosports.com,hohosports.com
_extra_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS += [h.strip() for h in _extra_hosts.split(",") if h.strip()]

# Render 會自動注入 xxx.onrender.com 這個內部網址
RENDER_HOST = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_HOST:
    ALLOWED_HOSTS.append(RENDER_HOST)

# Django 4+ 的 CSRF 需要完整 scheme；只信任真實網域（排除本機與 IP）
_LOCAL = {"localhost", "127.0.0.1", "[::1]", "testserver"}
CSRF_TRUSTED_ORIGINS = [
    f"https://{h}" for h in ALLOWED_HOSTS if h not in _LOCAL and not h[0].isdigit()
]


# Application definition

INSTALLED_APPS = [
    # 換成自訂的 AdminSite（只放行管理員；見 core/admin.py）
    'config.admin_apps.ATMAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方
    'rest_framework',
    'django_filters',

    # ATM 六大模組
    'core',
    'accounts',       # 模組1 Profile & 目標
    'planning',       # 模組2 日程與訓練計劃
    'training',       # 模組3 專項與力量
    'analytics',      # 模組4 數據分析
    'nutrition',      # 模組5 營養與恢復
    'injury',         # 模組6 傷患管理

    'programs',       # 公開報名（項目 / 報名表 → 匯入 ATM）
]

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

MIDDLEWARE = [
    # 最外層：後台與系統各用一份 session cookie，兩邊可同時登入不同帳號
    'core.zones.SplitAdminSessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # 正式環境靜態檔（CSS / Chart.js）
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_flags',
                'core.context_processors.athlete_nav',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 本機用 SQLite；Render 會提供 DATABASE_URL（PostgreSQL），自動切換。
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"          # collectstatic 的輸出目錄

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        # WhiteNoise：壓縮 + 加雜湊檔名，瀏覽器可長期快取
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "media/"
# Render 掛載持久磁碟時設 DJANGO_MEDIA_ROOT=/var/data/media，否則重新部署會遺失上傳檔
MEDIA_ROOT = Path(os.environ.get("DJANGO_MEDIA_ROOT", BASE_DIR / "media"))


# ------------------------------------------------------------ 正式環境安全性
if not DEBUG:
    # Render 在前面做 TLS 終結，靠這個 header 才知道原始請求是 https
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # Render 的健康檢查走內部 http，若被 301 轉去 https 會判定服務不健康
    SECURE_REDIRECT_EXEMPT = [r"^healthz$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30      # 先設 30 天，確認無誤後可調長
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# 跑測試時改用快速雜湊（PBKDF2 每次建帳號都要幾百毫秒）
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]

# --------------------------------------------------------------- 記錄檔
# Django 預設在 DEBUG=0 時把 500 的 traceback 交給 mail_admins；
# 沒設 ADMINS 就等於整個吞掉，Render 的 log 只會看到一行 500。
# 這裡明確把 django.request 的錯誤印到 stdout，讓 Render 看得到堆疊。
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "plain": {"format": "[{levelname}] {asctime} {name}: {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "plain"},
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        # 500 的完整 traceback
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # 被擋下來的登入嘗試（CSRF / DisallowedHost 等）
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------------------------------ 後台
# 後台網址可改：正式站設 DJANGO_ADMIN_URL=<不好猜的路徑>/，讓 /admin/ 直接 404。
ADMIN_URL = (os.environ.get("DJANGO_ADMIN_URL") or "admin/").strip().strip("/") + "/"

# 額外把後台鎖到指定帳號（逗號分隔）；留空表示「所有管理員帳號皆可」。
ADMIN_ALLOWED_USERS = [
    u.strip()
    for u in os.environ.get("DJANGO_ADMIN_ALLOWED_USERS", "").split(",")
    if u.strip()
]

# CSRF 失敗時給看得懂的頁面，而不是瀏覽器直接吐 403
CSRF_FAILURE_VIEW = "core.views.csrf_failure"

# 登入導向
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/app/'     # 登入後進系統，不是回公開首頁
LOGOUT_REDIRECT_URL = '/'        # 登出回公開首頁

# ATM 系統參數
ATM_DEFAULT_MACROCYCLE_WEEKS = 16
ATM_ACWR_SWEET_SPOT = (0.80, 1.30)
ATM_PAIN_BLOCK_THRESHOLD = 6
