# Generated by Django 6.0.4 on 2026-08-30 10:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('slug', models.SlugField(help_text='例：dbsac-sc-2026', max_length=60, unique=True, verbose_name='網址代碼')),
                ('title', models.CharField(max_length=150, verbose_name='項目名稱')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副標')),
                ('organiser', models.CharField(blank=True, default='DBSAC', max_length=100, verbose_name='主辦')),
                ('description', models.TextField(help_text='開頭段落，說明這個項目的背景與目的', verbose_name='項目說明')),
                ('schedule_text', models.CharField(blank=True, help_text='例：每週一，2026 年 9 月 9 日至 11 月 9 日', max_length=200, verbose_name='上課時間')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('session_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='課堂數')),
                ('group_note', models.CharField(blank=True, help_text='例：共 10 堂，分 2 組、每組 5 堂', max_length=200, verbose_name='分組方式')),
                ('capacity_per_session', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='每堂人數上限')),
                ('capacity_total', models.PositiveSmallIntegerField(blank=True, help_text='留空＝不限；額滿後新報名自動列為候補', null=True, verbose_name='總名額')),
                ('trainer', models.CharField(blank=True, max_length=100, verbose_name='教練')),
                ('recommended_for', models.CharField(blank=True, help_text='例：短跑、跨欄及中距離運動員', max_length=200, verbose_name='建議對象')),
                ('focus', models.TextField(blank=True, verbose_name='訓練重點')),
                ('venue_name', models.CharField(blank=True, max_length=120, verbose_name='場地')),
                ('venue_address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('venue_note', models.CharField(blank=True, max_length=200, verbose_name='交通')),
                ('price_hkd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='費用 (HK$)')),
                ('price_note', models.CharField(blank=True, max_length=200, verbose_name='費用說明')),
                ('important_note', models.TextField(blank=True, help_text='退款條款等，會以警示樣式顯示', verbose_name='重要事項')),
                ('contact_note', models.CharField(blank=True, help_text='例：WhatsApp +852 6531 2212', max_length=200, verbose_name='查詢方式')),
                ('status', models.CharField(choices=[('DRAFT', '草稿（不公開）'), ('OPEN', '開放報名'), ('CLOSED', '已截止'), ('ARCHIVED', '已封存')], default='DRAFT', max_length=10, verbose_name='狀態')),
                ('opens_at', models.DateTimeField(blank=True, help_text='留空＝立即開放', null=True, verbose_name='報名開始')),
                ('closes_at', models.DateTimeField(blank=True, help_text='留空＝不設限', null=True, verbose_name='報名截止')),
                ('display_order', models.SmallIntegerField(default=0, help_text='數字小的排前面', verbose_name='排序')),
            ],
            options={
                'verbose_name': '報名項目',
                'verbose_name_plural': '報名項目',
                'ordering': ['display_order', '-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文姓名')),
                ('name_zh', models.CharField(blank=True, max_length=60, verbose_name='中文姓名')),
                ('sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('phone', models.CharField(max_length=30, verbose_name='聯絡電話 / WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='電郵')),
                ('school_or_club', models.CharField(max_length=100, verbose_name='學校 / 會所')),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, help_text='預計或實際的中學畢業年份', null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)], verbose_name='學校畢業年份')),
                ('guardian_name', models.CharField(blank=True, max_length=100, verbose_name='家長／監護人姓名')),
                ('guardian_phone', models.CharField(blank=True, max_length=30, verbose_name='家長／監護人電話')),
                ('has_track_training', models.BooleanField(default=True, help_text='目前有恆常隊際或個人田徑訓練', verbose_name='現正參與田徑訓練')),
                ('event_category', models.CharField(choices=[('SPRINT', '短跑'), ('HURDLES', '跨欄'), ('MIDDLE', '中距離'), ('DISTANCE', '長距離'), ('JUMP', '跳部'), ('THROW', '投擲'), ('COMBINED', '全能'), ('RELAY', '接力')], default='SPRINT', max_length=15, verbose_name='項目分類')),
                ('personal_best', models.CharField(blank=True, help_text='例：100m 11.42（2026 年 4 月）', max_length=100, verbose_name='個人最佳成績')),
                ('training_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='田徑訓練年資 (年)')),
                ('training_days_per_week', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='每週訓練日數')),
                ('strength_experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='重量訓練年資 (年)')),
                ('current_coach', models.CharField(blank=True, max_length=100, verbose_name='現任教練')),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='身高 (cm)')),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='體重 (kg)')),
                ('emergency_contact_name', models.CharField(max_length=100, verbose_name='緊急聯絡人')),
                ('emergency_contact_phone', models.CharField(max_length=30, verbose_name='緊急聯絡電話')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=40, verbose_name='關係')),
                ('has_current_injury', models.BooleanField(default=False, verbose_name='目前有傷患或痛症')),
                ('injury_detail', models.TextField(blank=True, help_text='部位、發生時間、目前狀況', verbose_name='傷患描述')),
                ('injury_history', models.TextField(blank=True, verbose_name='過往重大傷患')),
                ('medical_conditions', models.TextField(blank=True, help_text='哮喘、心臟／血壓問題、癲癇等', verbose_name='長期病患')),
                ('medications', models.CharField(blank=True, max_length=200, verbose_name='長期服用藥物')),
                ('allergies', models.CharField(blank=True, max_length=200, verbose_name='敏感 / 過敏')),
                ('doctor_clearance', models.BooleanField(default=True, help_text='若有長期病患或傷患，須先諮詢醫生', verbose_name='已取得醫生許可參與訓練')),
                ('health_declaration', models.BooleanField(default=False, verbose_name='健康申報屬實')),
                ('consent_terms', models.BooleanField(default=False, verbose_name='已閱讀並同意項目條款（包括不設退款）')),
                ('consent_data', models.BooleanField(default=False, verbose_name='同意資料用於訓練管理與聯絡')),
                ('remarks', models.TextField(blank=True, verbose_name='其他想讓教練知道的事')),
                ('status', models.CharField(choices=[('NEW', '待處理'), ('CONFIRMED', '已確認'), ('WAITLIST', '候補'), ('CANCELLED', '已取消')], default='NEW', max_length=10, verbose_name='處理狀態')),
                ('internal_note', models.TextField(blank=True, help_text='只有後台看得到', verbose_name='內部備註')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='匯入 ATM 時間')),
                ('athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='accounts.athleteprofile', verbose_name='已匯入的運動員')),
                ('primary_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.event', verbose_name='主項')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.project', verbose_name='報名項目')),
            ],
            options={
                'verbose_name': '報名表',
                'verbose_name_plural': '報名表',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'email'), name='unique_application_per_project_email')],
            },
        ),
    ]
