# Generated by Django 6.0.4 on 2026-08-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='guardian_phone',
        ),
        migrations.AlterField(
            model_name='application',
            name='school_or_club',
            field=models.CharField(default='DBSAC', help_text='預設為 DBSAC，教練可在後台修改', max_length=100, verbose_name='學校 / 體育會'),
        ),
    ]
