# Generated by Django 6.0.4 on 2026-09-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_application_guardian_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_school_or_club',
            field=models.CharField(blank=True, help_text='報名表「學校 / 體育會」的預設值，留空＝沿用 DBSAC；報名者仍可自行修改', max_length=100, verbose_name='預設學校 / 體育會'),
        ),
    ]
