# Generated by Django 6.0.4 on 2026-09-01 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('programs', '0003_project_default_school_or_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='athlete',
            field=models.ForeignKey(blank=True, help_text='同一名運動員可以報多個項目，全部報名表都指向同一份檔案', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='accounts.athleteprofile', verbose_name='已匯入的運動員'),
        ),
    ]
