# Generated by Django 6.0.4 on 2026-09-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_bodymetriclog_options_bodymetriclog_bmi_and_more'),
        ('programs', '0004_alter_application_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coaches',
            field=models.ManyToManyField(blank=True, help_text='這個計劃由哪些教練帶；同一名運動員在不同計劃可以由不同教練負責，每位負責教練都看得到他的狀態總覽', related_name='coached_projects', to='accounts.coachprofile', verbose_name='負責教練'),
        ),
    ]
