# Generated by Django 6.0.4 on 2026-09-10 03:47

import django.core.validators
import django.db.models.deletion
import video.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_bodymetriclog_body_fat_mass_kg_bodymetriclog_brand_and_more'),
        ('analytics', '0012_alter_metricitem_domain'),
        ('training', '0007_blockprogram_blockprogramitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='拍攝日期')),
                ('kind', models.CharField(choices=[('SPRINT', '跑步／專項'), ('STRENGTH', '重量訓練'), ('DRILL', '技術練習'), ('OTHER', '其他')], default='STRENGTH', max_length=12, verbose_name='類別')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='標題')),
                ('note', models.TextField(blank=True, verbose_name='說明')),
                ('file', models.FileField(blank=True, help_text='經 Django 上傳的檔案（本機開發用）', upload_to=video.models.video_upload_to, verbose_name='影片檔')),
                ('remote_key', models.CharField(blank=True, help_text='瀏覽器直傳 R2 時的 key，不經過 Django', max_length=255, verbose_name='R2 物件位置')),
                ('poster', models.ImageField(blank=True, upload_to=video.models.poster_upload_to, verbose_name='縮圖')),
                ('duration_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='長度 (秒)')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='檔案大小')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='寬')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='高')),
                ('is_keeper', models.BooleanField(default=False, help_text='勾了就不會被保留期限自動清掉（見 purge_videos）', verbose_name='保留為範本')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='training.sessionactivity', verbose_name='對應課表活動')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='accounts.athleteprofile', verbose_name='運動員')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='analytics.metricrecord', verbose_name='對應數據紀錄')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '訓練影片',
                'verbose_name_plural': '訓練影片',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('at_sec', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='時間點 (秒)')),
                ('body', models.TextField(verbose_name='批註')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_notes', to=settings.AUTH_USER_MODEL, verbose_name='批註者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='video.trainingvideo', verbose_name='影片')),
            ],
            options={
                'verbose_name': '影片批註',
                'verbose_name_plural': '影片批註',
                'ordering': ['at_sec', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingvideo',
            index=models.Index(fields=['athlete', 'date'], name='video_train_athlete_5ca6ea_idx'),
        ),
    ]
