# Generated by Django 6.0.4 on 2026-09-10 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonote',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='量測資料'),
        ),
        migrations.AddField(
            model_name='videonote',
            name='end_sec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='結束時間 (秒)'),
        ),
    ]
