# Generated by Django 6.0.4 on 2026-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videonote_data_videonote_end_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuotaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_max_videos', models.PositiveSmallIntegerField(default=12, help_text='0 ＝ 不限', verbose_name='免費：條數上限')),
                ('free_max_mb', models.PositiveIntegerField(default=600, help_text='0 ＝ 不限', verbose_name='免費：容量上限 (MB)')),
                ('free_retain_days', models.PositiveSmallIntegerField(default=90, help_text='purge_videos 會清掉超過這個天數、且未標為範本的片；0 ＝ 不清', verbose_name='免費：保留天數')),
                ('pro_max_videos', models.PositiveSmallIntegerField(default=60, help_text='0 ＝ 不限', verbose_name='進階：條數上限')),
                ('pro_max_mb', models.PositiveIntegerField(default=3072, help_text='0 ＝ 不限', verbose_name='進階：容量上限 (MB)')),
                ('pro_retain_days', models.PositiveSmallIntegerField(default=365, help_text='0 ＝ 不清', verbose_name='進階：保留天數')),
            ],
            options={
                'verbose_name': '影片額度設定',
                'verbose_name_plural': '影片額度設定',
            },
        ),
    ]
