# Generated by Django 6.0.4 on 2026-09-12 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_athleteprofile_video_max_mb_and_more'),
        ('video', '0003_videoquotaconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanUpgradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('contact', models.CharField(blank=True, help_text='留空就用帳號上的電話', max_length=60, verbose_name='聯絡電話 / WhatsApp')),
                ('note', models.TextField(blank=True, verbose_name='申請原因')),
                ('status', models.CharField(choices=[('NEW', '待聯絡'), ('APPROVED', '已開通'), ('DECLINED', '已婉拒')], default='NEW', max_length=10, verbose_name='狀態')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('admin_note', models.TextField(blank=True, help_text='收了多少、談了什麼；運動員看不到', verbose_name='內部備註')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_requests', to='accounts.athleteprofile', verbose_name='運動員')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_requests_handled', to=settings.AUTH_USER_MODEL, verbose_name='處理人')),
                ('requested_by', models.ForeignKey(blank=True, help_text='運動員自己按的，或教練代按的', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
            ],
            options={
                'verbose_name': '進階會員申請',
                'verbose_name_plural': '進階會員申請',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'NEW')), fields=('athlete',), name='one_open_upgrade_request_per_athlete')],
            },
        ),
    ]
