# Generated by Django 6.0.4 on 2026-09-13 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_athleteprofile_video_max_mb_and_more'),
        ('programs', '0005_project_coaches'),
        ('video', '0004_planupgraderequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_shared_to_me', to='accounts.athleteprofile', verbose_name='分享給')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_shares', to='programs.project', verbose_name='經由計劃')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_shares_made', to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='video.trainingvideo', verbose_name='影片')),
            ],
            options={
                'verbose_name': '影片分享',
                'verbose_name_plural': '影片分享',
                'ordering': ['athlete__user__username', 'id'],
                'constraints': [models.UniqueConstraint(fields=('video', 'athlete'), name='one_share_per_video_athlete')],
            },
        ),
    ]
