# Generated by Django 6.0.4 on 2026-08-09 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='代碼')),
                ('name_zh', models.CharField(max_length=60, verbose_name='中文名稱')),
                ('name_en', models.CharField(max_length=80, verbose_name='英文名稱')),
                ('category', models.CharField(choices=[('SQUAT', '蹲系'), ('HINGE', '髖鉸鏈'), ('PUSH', '推'), ('PULL', '拉'), ('OLYMPIC', '奧舉'), ('PLYO', '增強式'), ('CORE', '核心'), ('UNILATERAL', '單邊'), ('ACCESSORY', '輔助'), ('REHAB', '復健')], max_length=12, verbose_name='分類')),
                ('is_measured_by_1rm', models.BooleanField(default=True, verbose_name='以 1RM 計算強度')),
                ('is_plyometric', models.BooleanField(default=False, verbose_name='增強式動作')),
                ('primary_muscles', models.CharField(blank=True, max_length=120, verbose_name='主要肌群')),
                ('video_url', models.URLField(blank=True, verbose_name='示範影片')),
            ],
            options={
                'verbose_name': '力量動作',
                'verbose_name_plural': '力量動作',
                'ordering': ['category', 'name_zh'],
            },
        ),
        migrations.CreateModel(
            name='StrengthSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='動作排序')),
                ('set_number', models.PositiveSmallIntegerField(default=1, verbose_name='第幾組')),
                ('reps', models.PositiveSmallIntegerField(verbose_name='次數')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='重量 (kg)')),
                ('target_1rm_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='目標強度 (% 1RM)')),
                ('actual_1rm_pct', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=5, null=True, verbose_name='實際強度 (% 1RM)')),
                ('tempo', models.CharField(blank=True, help_text='例：3-1-X-0', max_length=15, verbose_name='節奏')),
                ('rest_sec', models.PositiveIntegerField(default=120, verbose_name='組間休息 (秒)')),
                ('rir', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='RIR 保留次數')),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE (1-10)')),
                ('bar_velocity_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='槓速 (m/s)')),
                ('is_failure', models.BooleanField(default=False, verbose_name='力竭')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='備註')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strength_sets', to='training.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_sets', to='planning.trainingsession')),
            ],
            options={
                'verbose_name': '力量訓練組',
                'verbose_name_plural': '力量訓練組',
                'ordering': ['session', 'order', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='TrackSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('description', models.CharField(help_text='例：6 × 200m', max_length=150, verbose_name='描述')),
                ('distance_m', models.PositiveIntegerField(verbose_name='單趟距離 (m)')),
                ('reps', models.PositiveSmallIntegerField(default=1, verbose_name='趟數')),
                ('sets', models.PositiveSmallIntegerField(default=1, verbose_name='組數')),
                ('target_time_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='目標時間 (秒)')),
                ('actual_time_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='實際平均時間 (秒)')),
                ('rest_between_reps_sec', models.PositiveIntegerField(default=0, verbose_name='趟間休息 (秒)')),
                ('rest_between_sets_sec', models.PositiveIntegerField(default=0, verbose_name='組間休息 (秒)')),
                ('intensity_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='強度 (% PB)')),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='平均心率')),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='最高心率')),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='RPE (1-10)')),
                ('technical_focus', models.TextField(blank=True, verbose_name='技術重點')),
                ('surface', models.CharField(choices=[('TRACK', '田徑場'), ('GRASS', '草地'), ('HILL', '斜坡'), ('TREADMILL', '跑步機'), ('ROAD', '路跑'), ('SAND', '沙地')], default='TRACK', max_length=10, verbose_name='場地')),
                ('spikes_used', models.BooleanField(default=False, verbose_name='穿釘鞋')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_sets', to='planning.trainingsession')),
            ],
            options={
                'verbose_name': '專項訓練組',
                'verbose_name_plural': '專項訓練組',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='NeuromuscularTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('date', models.DateField(verbose_name='日期')),
                ('test_type', models.CharField(choices=[('CMJ', '反向跳 CMJ (cm)'), ('SJ', '蹲跳 SJ (cm)'), ('BROAD_JUMP', '立定跳遠 (cm)'), ('GRIP', '握力 (kg)'), ('SPRINT_10M', '10m 衝刺 (秒)')], max_length=15, verbose_name='測試項目')),
                ('value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='數值')),
                ('unit', models.CharField(default='cm', max_length=10, verbose_name='單位')),
                ('note', models.CharField(blank=True, max_length=150, verbose_name='備註')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nm_tests', to='accounts.athleteprofile')),
            ],
            options={
                'verbose_name': '神經肌肉測試',
                'verbose_name_plural': '神經肌肉測試',
                'ordering': ['-date'],
                'unique_together': {('athlete', 'date', 'test_type')},
            },
        ),
        migrations.CreateModel(
            name='OneRepMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('value_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='1RM (kg)')),
                ('test_date', models.DateField(verbose_name='測試日期')),
                ('is_estimated', models.BooleanField(default=False, verbose_name='推估值')),
                ('estimation_formula', models.CharField(choices=[('EPLEY', 'Epley'), ('BRZYCKI', 'Brzycki'), ('DIRECT', '實測')], default='DIRECT', max_length=10, verbose_name='推估公式')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_rms', to='accounts.athleteprofile')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_rms', to='training.exercise')),
            ],
            options={
                'verbose_name': '最大肌力 1RM',
                'verbose_name_plural': '最大肌力 1RM',
                'ordering': ['-test_date'],
                'unique_together': {('athlete', 'exercise', 'test_date')},
            },
        ),
        migrations.CreateModel(
            name='RepSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_number', models.PositiveSmallIntegerField(verbose_name='第幾趟')),
                ('time_sec', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='時間 (秒)')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='備註')),
                ('track_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='training.trackset')),
            ],
            options={
                'verbose_name': '分趟成績',
                'verbose_name_plural': '分趟成績',
                'ordering': ['rep_number'],
                'unique_together': {('track_set', 'rep_number')},
            },
        ),
    ]
