# Generated by Django 6.0.4 on 2026-08-31 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_trainingsession_created_by_and_more'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='活動名稱')),
                ('default_block', models.CharField(choices=[('WARMUP', '熱身'), ('MAIN', '正課'), ('SUPPLEMENT', '補充練習'), ('RECOVERY', '恢復練習')], default='WARMUP', max_length=12, verbose_name='預設區塊')),
                ('default_sets', models.CharField(blank=True, max_length=30, verbose_name='預設組數')),
                ('default_reps', models.CharField(blank=True, max_length=30, verbose_name='預設次數')),
                ('default_distance', models.CharField(blank=True, max_length=30, verbose_name='預設距離')),
                ('default_weight', models.CharField(blank=True, max_length=40, verbose_name='預設重量')),
                ('default_intensity', models.CharField(blank=True, max_length=40, verbose_name='預設強度')),
                ('default_rest', models.CharField(blank=True, max_length=80, verbose_name='預設休息時間')),
                ('default_key_points', models.TextField(blank=True, verbose_name='預設訓練要點')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='系統內建')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='使用次數')),
                ('is_active', models.BooleanField(default=True, verbose_name='可挑選')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_definitions', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '訓練活動',
                'verbose_name_plural': '訓練活動',
                'ordering': ['default_block', '-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('block', models.CharField(choices=[('WARMUP', '熱身'), ('MAIN', '正課'), ('SUPPLEMENT', '補充練習'), ('RECOVERY', '恢復練習')], max_length=12, verbose_name='區塊')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('name', models.CharField(max_length=120, verbose_name='活動名稱')),
                ('sets', models.CharField(blank=True, max_length=30, verbose_name='組數')),
                ('reps', models.CharField(blank=True, max_length=30, verbose_name='次數')),
                ('distance', models.CharField(blank=True, max_length=30, verbose_name='距離')),
                ('weight', models.CharField(blank=True, max_length=40, verbose_name='重量')),
                ('intensity', models.CharField(blank=True, max_length=40, verbose_name='強度')),
                ('rest', models.CharField(blank=True, max_length=80, verbose_name='休息時間')),
                ('key_points', models.TextField(blank=True, verbose_name='訓練要點')),
                ('note', models.TextField(blank=True, verbose_name='當日備注')),
                ('satisfaction', models.PositiveSmallIntegerField(blank=True, help_text='完成後自評對這項訓練的滿意程度', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='滿意度 (1-5)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_activities', to=settings.AUTH_USER_MODEL, verbose_name='寫入者')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uses', to='training.activitydefinition', verbose_name='來源活動')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planning.trainingsession')),
            ],
            options={
                'verbose_name': '課表活動',
                'verbose_name_plural': '課表活動',
                'ordering': ['session', 'block', 'order', 'id'],
                'indexes': [models.Index(fields=['session', 'block', 'order'], name='training_se_session_dbce4e_idx')],
            },
        ),
    ]
