# Generated by Django 6.0.4 on 2026-09-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_activitydefinition_sessionactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydefinition',
            options={'ordering': ['category', 'default_block', '-use_count', 'name'], 'verbose_name': '訓練活動', 'verbose_name_plural': '訓練活動'},
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='category',
            field=models.CharField(choices=[('WARMUP', '熱身'), ('TRACK', '田徑專項'), ('UPPER', '上肢力量'), ('LOWER', '下肢力量'), ('CORE', '核心'), ('PLYO', '增強式／爆發力'), ('ACCESSORY', '輔助／預防傷害'), ('RECOVERY', '恢復／放鬆')], default='WARMUP', max_length=12, verbose_name='分類'),
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='name_en',
            field=models.CharField(blank=True, help_text='健身房器材與課表上常寫英文，兩個名字都留著才找得到', max_length=120, verbose_name='英文名稱'),
        ),
    ]
