# Generated by Django 6.0.4 on 2026-09-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_activitydefinition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydefinition',
            name='category',
            field=models.CharField(choices=[('WARMUP', '熱身'), ('TRACK', '田徑專項'), ('UPPER', '上肢力量'), ('LOWER', '下肢力量'), ('CORE', '核心'), ('PLYO', '增強式／爆發力'), ('PLYO_BASIC', '增強式：基礎與進階跳躍'), ('PLYO_TRACK', '增強式：田徑專項'), ('PLYO_UPPER', '增強式：上肢與全身旋轉'), ('PLYO_POGO', '增強式：踝彈跳 Pogo'), ('ACCESSORY', '輔助／預防傷害'), ('RECOVERY', '恢復／放鬆')], default='WARMUP', max_length=12, verbose_name='分類'),
        ),
    ]
