# Generated by Django 6.0.4 on 2026-09-05 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_activitydefinition_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='status',
            field=models.CharField(choices=[('PENDING', '待管理員確認'), ('APPROVED', '已確認'), ('REJECTED', '已退回')], default='APPROVED', max_length=10, verbose_name='狀態'),
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=60, verbose_name='名稱')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='英文名稱')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('order', models.PositiveSmallIntegerField(default=50, verbose_name='排序')),
                ('status', models.CharField(choices=[('PENDING', '待管理員確認'), ('APPROVED', '已確認'), ('REJECTED', '已退回')], default='APPROVED', max_length=10, verbose_name='狀態')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='系統內建')),
                ('activity_category', models.CharField(choices=[('WARMUP', '熱身'), ('TRACK', '田徑專項'), ('UPPER', '上肢力量'), ('LOWER', '下肢力量'), ('CORE', '核心'), ('PLYO', '增強式／爆發力'), ('PLYO_BASIC', '增強式：基礎與進階跳躍'), ('PLYO_TRACK', '增強式：田徑專項'), ('PLYO_UPPER', '增強式：上肢與全身旋轉'), ('PLYO_POGO', '增強式：踝彈跳 Pogo'), ('ACCESSORY', '輔助／預防傷害'), ('RECOVERY', '恢復／放鬆')], default='WARMUP', help_text='這個項目底下新加的動作預設算哪一類——決定數據分析把它歸到哪個範疇', max_length=12, verbose_name='預設分類')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '運動項目',
                'verbose_name_plural': '運動項目',
                'ordering': ['sport__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='training.discipline', verbose_name='運動項目'),
        ),
        migrations.CreateModel(
            name='MovementKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='英文名稱')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('order', models.PositiveSmallIntegerField(default=50, verbose_name='排序')),
                ('status', models.CharField(choices=[('PENDING', '待管理員確認'), ('APPROVED', '已確認'), ('REJECTED', '已退回')], default='APPROVED', max_length=10, verbose_name='狀態')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='系統內建')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='訓練動作種類')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '訓練動作種類',
                'verbose_name_plural': '訓練動作種類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='movement_kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='training.movementkind', verbose_name='訓練動作種類'),
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='英文名稱')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('order', models.PositiveSmallIntegerField(default=50, verbose_name='排序')),
                ('status', models.CharField(choices=[('PENDING', '待管理員確認'), ('APPROVED', '已確認'), ('REJECTED', '已退回')], default='APPROVED', max_length=10, verbose_name='狀態')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='系統內建')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='運動種類')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '運動種類',
                'verbose_name_plural': '運動種類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='training.sporttype', verbose_name='運動種類'),
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('sport', 'name')},
        ),
    ]
