# Generated by Django 6.0.4 on 2026-09-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_activitydefinition_status_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='extra_disciplines',
            field=models.ManyToManyField(blank=True, help_text='同一個動作常常好幾種運動都在練（例：深蹲在田徑與體能訓練都用得到）', related_name='extra_activities', to='training.discipline', verbose_name='也屬於的運動項目'),
        ),
    ]
