# Generated by Django 6.0.4 on 2026-09-09 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_activitydefinition_extra_disciplines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=120, verbose_name='program 名稱')),
                ('block', models.CharField(choices=[('WARMUP', '熱身'), ('MAIN', '正課'), ('SUPPLEMENT', '補充練習'), ('RECOVERY', '恢復練習')], max_length=12, verbose_name='區塊')),
                ('session_type', models.CharField(blank=True, help_text='存下來時那一堂課的課別，只作提示', max_length=20, verbose_name='來源課別')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='套用次數')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_programs', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '區塊 program',
                'verbose_name_plural': '區塊 program',
                'ordering': ['block', '-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlockProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('name', models.CharField(max_length=120, verbose_name='活動名稱')),
                ('sets', models.CharField(blank=True, max_length=30, verbose_name='組數')),
                ('reps', models.CharField(blank=True, max_length=30, verbose_name='次數')),
                ('distance', models.CharField(blank=True, max_length=30, verbose_name='距離')),
                ('weight', models.CharField(blank=True, max_length=40, verbose_name='重量')),
                ('intensity', models.CharField(blank=True, max_length=40, verbose_name='強度')),
                ('rest', models.CharField(blank=True, max_length=80, verbose_name='休息時間')),
                ('key_points', models.TextField(blank=True, verbose_name='訓練要點')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_items', to='training.activitydefinition', verbose_name='來源活動')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='training.blockprogram', verbose_name='program')),
            ],
            options={
                'verbose_name': 'program 活動',
                'verbose_name_plural': 'program 活動',
                'ordering': ['program', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='blockprogram',
            constraint=models.UniqueConstraint(fields=('created_by', 'block', 'name'), name='unique_block_program_per_owner'),
        ),
    ]
